program M2Server;

uses
  FastMM4,
  Forms,
  Windows,
  Graphics,
  svMain in 'svMain.pas' {FrmMain},
  LocalDB in 'LocalDB.pas' {FrmDB},
  InterServerMsg in 'InterServerMsg.pas' {FrmSrvMsg},
  InterMsgClient in 'InterMsgClient.pas' {FrmMsgClient},
  IdSrvClient in 'IdSrvClient.pas' {FrmIDSoc},
  FSrvValue in 'FSrvValue.pas' {FrmServerValue},
  UsrEngn in 'UsrEngn.pas',
  ObjNpc in 'ObjNpc.pas',
  ObjMon3 in 'ObjMon3.pas',
  ObjMon2 in 'ObjMon2.pas',
  ObjMon in 'ObjMon.pas',
  ObjGuard in 'ObjGuard.pas',
  ObjBase in 'ObjBase.pas',
  ObjAxeMon in 'ObjAxeMon.pas',
  NoticeM in 'NoticeM.pas',
  Mission in 'Mission.pas',
  Magic in 'Magic.pas',
  M2Share in 'M2Share.pas',
  ItmUnit in 'ItmUnit.pas',
  Guild in 'Guild.pas',
  FrnEngn in 'FrnEngn.pas',
  Event in 'Event.pas',
  Envir in 'Envir.pas',
  Castle in 'Castle.pas',
  RunDB in 'RunDB.pas',
  RunSock in 'RunSock.pas',
  MudUtil in 'MudUtil.pas',
  GeneralConfig in 'GeneralConfig.pas' {frmGeneralConfig},
  GameConfig in 'GameConfig.pas' {frmGameConfig},
  FunctionConfig in 'FunctionConfig.pas' {frmFunctionConfig},
  ObjRobot in 'ObjRobot.pas',
  BnkEngn in 'BnkEngn.pas',
  ViewSession in 'ViewSession.pas' {frmViewSession},
  ViewOnlineHuman in 'ViewOnlineHuman.pas' {frmViewOnlineHuman},
  ViewLevel in 'ViewLevel.pas' {frmViewLevel},
  ViewList in 'ViewList.pas' {frmViewList},
  OnlineMsg in 'OnlineMsg.pas' {frmOnlineMsg},
  HumanInfo in 'HumanInfo.pas' {frmHumanInfo},
  ViewKernelInfo in 'ViewKernelInfo.pas' {frmViewKernelInfo},
  ConfigMerchant in 'ConfigMerchant.pas' {frmConfigMerchant},
  ItemSet in 'ItemSet.pas' {frmItemSet},
  ConfigMonGen in 'ConfigMonGen.pas' {frmConfigMonGen},
  GameCommand in 'GameCommand.pas' {frmGameCmd},
  MonsterConfig in 'MonsterConfig.pas' {frmMonsterConfig},
  ActionSpeedConfig in 'ActionSpeedConfig.pas' {frmActionSpeed},
  CastleManage in 'CastleManage.pas' {frmCastleManage},
  CastleAttackEdit in 'CastleAttackEdit.pas' {FormCastleAttackEdit},
  NpcCustomU in 'NpcCustomU.pas' {ftmNpcCustom},
  StartPointManage in 'StartPointManage.pas',
  PlugIn in 'PlugIn.pas',
  Grobal2 in '..\Common\Grobal2.pas',
  EDcode in '..\Common\EDcode.pas',
  SDK in '..\Common\SDK.pas',
  bDiaLogs in 'bDiaLogs.pas',
  HUtil32 in '..\Common\HUtil32.pas',
  EngineAPI in 'Plug-in\PlugInCommon\EngineAPI.pas',
  EngineType in 'Plug-in\PlugInCommon\EngineType.pas',
  MD5 in '..\Common\MD5.pas',
  ObjectHero in 'ObjectHero.pas',
  __DESUnit in '..\Common\__DESUnit.pas',
  AdaptersInfo in '..\Common\AdaptersInfo.pas',
  WinlicenseSDK in '..\Common\WinlicenseSDK.pas',
  ObjectHeroMon in 'ObjectHeroMon.pas',
  DBSQL in 'DBSQL.pas',
  SqlEngn in 'SqlEngn.pas',
  MaketSystem in 'MaketSystem.pas',
  HashList in '..\Common\HashList.pas',
  StallSystem in '..\Common\StallSystem.pas',
  SELicenseSDK in '..\Common\SELicenseSDK.pas',
  SESDK in '..\Common\SESDK.pas',
  ObjMon5 in 'ObjMon5.pas',
  VMProtectSDK in '..\Common\VMProtectSDK.pas',
  HWIDFilter in 'HWIDFilter.pas',
  uCheck in 'uCheck.pas';

{$R *.res}

{
  USEWLSDK 这个还要再次检查 
}
{
exports
  TList_Create Name 'TList_Create',
  TList_Free Name 'TList_Free',
  TList_Count Name 'TList_Count',
  TList_Add Name 'TList_Add',
  TList_Insert Name 'TList_Insert',
  TList_Get Name 'TList_Get',
  TList_Put Name 'TList_Put',
  TList_Delete Name 'TList_Delete',
  TList_Clear Name 'TList_Delete',
  TList_Exchange Name 'TList_Delete',
  TStringList_Create Name 'TStringList_Create',
  TStringList_Free Name 'TStringList_Free',
  TStringList_Count Name 'TStringList_Count',
  TStringList_Add Name 'TStringList_Add',
  TStringList_AddObject Name 'TStringList_AddObject',
  TStringList_Insert Name 'TStringList_Insert',
  TStringList_Get Name 'TStringList_Get',
  TStringList_GetObject Name 'TStringList_GetObject',
  TStringList_Put Name 'TStringList_Put',
  TStringList_PutObject Name 'TStringList_PutObject',
  TStringList_Delete Name 'TStringList_Delete',
  TStringList_Clear Name 'TStringList_Clear',
  TStringList_Exchange Name 'TStringList_Exchange',
  TStringList_LoadFormFile Name 'TStringList_Exchange',
  TStringList_SaveToFile Name 'TStringList_Exchange',
  MainOutMessage Name 'MainOutMessageAPI',
  AddGameDataLog Name 'AddGameDataLogAPI',
  GetGameGoldName Name 'GetGameGoldName',
  EDcode_Decode6BitBuf Name 'EDcode_Decode6BitBuf',
  EDcode_Encode6BitBuf Name 'EDcode_Encode6BitBuf',
  EDcode_SetDecode Name 'EDcode_SetDecode',
  EDcode_SetEncode Name 'EDcode_SetEncode',
  EDcode_EncodeString Name 'EDcode_EnCodeString',
  EDcode_DecodeString Name 'EDcode_DeCodeString',
  EDcode_EncodeBuffer Name 'EDcode_EncodeBuffer',
  EDcode_DecodeBuffer Name 'EDcode_DecodeBuffer',
  TConfig_sEnvirDir Name 'TConfig_sEnvirDir',
  TBaseObject_Create Name 'TBaseObject_Create',
  TBaseObject_Free Name 'TBaseObject_Free',
  TBaseObject_sMapFileName Name 'TBaseObject_sMapFileName',
  TBaseObject_sMapName Name 'TBaseObject_sMapName',
  TBaseObject_sMapNameA Name 'TBaseObject_sMapNameA',
  TBaseObject_sCharName Name 'TBaseObject_sCharName',
  TBaseObject_sCharNameA Name 'TBaseObject_sCharNameA',
  TBaseObject_nCurrX Name 'TBaseObject_nCurrX',
  TBaseObject_nCurrY Name 'TBaseObject_nCurrY',
  TBaseObject_btDirection Name 'TBaseObject_btDirection',
  TBaseObject_btGender Name 'TBaseObject_btGender',
  TBaseObject_btHair Name 'TBaseObject_btHair',
  TBaseObject_btJob Name 'TBaseObject_btJob',
  TBaseObject_nGold Name 'TBaseObject_nGold',
  TBaseObject_Ability Name 'TBaseObject_Ability',
  TBaseObject_WAbility Name 'TBaseObject_WAbility',
  TBaseObject_nCharStatus Name 'TBaseObject_nCharStatus',
  TBaseObject_sHomeMap Name 'TBaseObject_sHomeMap',
  TBaseObject_nHomeX Name 'TBaseObject_nHomeX',
  TBaseObject_nHomeY Name 'TBaseObject_nHomeY',
  TBaseObject_boOnHorse Name 'TBaseObject_boOnHorse',
  TBaseObject_btHorseType Name 'TBaseObject_btHorseType',
  TBaseObject_btDressEffType Name 'TBaseObject_btDressEffType',
  TBaseObject_nPkPoint Name 'TBaseObject_nPkPoint',
  TBaseObject_boAllowGroup Name 'TBaseObject_boAllowGroup',
  TBaseObject_boAllowGuild Name 'TBaseObject_boAllowGuild',
  TBaseObject_nFightZoneDieCount Name 'TBaseObject_nFightZoneDieCount',
  TBaseObject_nBonusPoint Name 'TBaseObject_nBonusPoint',
  TBaseObject_nHungerStatus Name 'TBaseObject_nHungerStatus',
  TBaseObject_boAllowGuildReCall Name 'TBaseObject_boAllowGuildReCall',
  TBaseObject_duBodyLuck Name 'TBaseObject_duBodyLuck',
  TBaseObject_nBodyLuckLevel Name 'TBaseObject_nBodyLuckLevel',
  TBaseObject_wGroupRcallTime Name 'TBaseObject_wGroupRcallTime',
  TBaseObject_boAllowGroupReCall Name 'TBaseObject_boAllowGroupReCall',
  TBaseObject_nCharStatusEx Name 'TBaseObject_nCharStatusEx',
  TBaseObject_dwFightExp Name 'TBaseObject_dwFightExp',
  TBaseObject_nViewRange Name 'TBaseObject_nViewRange',
  TBaseObject_wAppr Name 'TBaseObject_wAppr',
  TBaseObject_btRaceServer Name 'TBaseObject_btRaceServer',
  TBaseObject_btRaceImg Name 'TBaseObject_btRaceImg',
  TBaseObject_btHitPoint Name 'TBaseObject_btHitPoint',
  TBaseObject_nHitPlus Name 'TBaseObject_nHitPlus',
  TBaseObject_nHitDouble Name 'TBaseObject_nHitDouble',
  TBaseObject_boRecallSuite Name 'TBaseObject_boRecallSuite',
  TBaseObject_nHealthRecover Name 'TBaseObject_nHealthRecover',
  TBaseObject_nSpellRecover Name 'TBaseObject_nSpellRecover',
  TBaseObject_btAntiPoison Name 'TBaseObject_btAntiPoison',
  TBaseObject_nPoisonRecover Name 'TBaseObject_nPoisonRecover',
  TBaseObject_nAntiMagic Name 'TBaseObject_nAntiMagic',
  TBaseObject_nLuck Name 'TBaseObject_nLuck',
  TBaseObject_nPerHealth Name 'TBaseObject_nPerHealth',
  TBaseObject_nPerHealing Name 'TBaseObject_nPerHealing',
  TBaseObject_nPerSpell Name 'TBaseObject_nPerSpell',
  TBaseObject_btGreenPoisoningPoint Name 'TBaseObject_btGreenPoisoningPoint',
  TBaseObject_nGoldMax Name 'TBaseObject_nGoldMax',
  TBaseObject_btSpeedPoint Name 'TBaseObject_btSpeedPoint',
  TBaseObject_btPermission Name 'TBaseObject_btPermission',
  TBaseObject_nHitSpeed Name 'TBaseObject_nHitSpeed',
  TBaseObject_TargetCret Name 'TBaseObject_TargetCret',
  TBaseObject_LastHiter Name 'TBaseObject_LastHiter',
  TBaseObject_ExpHiter Name 'TBaseObject_ExpHitter',
  TBaseObject_btLifeAttrib Name 'TBaseObject_btLifeAttrib',
  TBaseObject_GroupOwner Name 'TBaseObject_GroupOwner',
  TBaseObject_GroupMembersList Name 'TBaseObject_GroupMembersList',
  TBaseObject_boHearWhisper Name 'TBaseObject_boHearWhisper',
  TBaseObject_boBanShout Name 'TBaseObject_boBanShout',
  TBaseObject_boBanGuildChat Name 'TBaseObject_boBanGuildChat',
  TBaseObject_boAllowDeal Name 'TBaseObject_boAllowDeal',
  //TBaseObject_nSlaveType Name 'TBaseObject_nSlaveType',
  TBaseObject_Master Name 'TBaseObject_Master',
  TBaseObject_btAttatckMode Name 'TBaseObject_btAttatckMode',
  TBaseObject_nNameColor Name 'TBaseObject_nNameColor',
  TBaseObject_nLight Name 'TBaseObject_nLight',
  TBaseObject_ItemList Name 'TBaseObject_ItemList',
  TBaseObject_MagicList Name 'TBaseObject_MagicList',
  TBaseObject_MyGuild Name 'TBaseObject_MyGuild',
  TBaseObject_UseItems Name 'TBaseObject_UseItems',
  TBaseObject_btMonsterWeapon Name 'TBaseObject_btMonsterWeapon',
  TBaseObject_PEnvir Name 'TBaseObject_PEnvir',
  TBaseObject_boGhost Name 'TBaseObject_boGhost',
  TBaseObject_boDeath Name 'TBaseObject_boDeath',
  TBaseObject_boNoItem Name 'TBaseObject_boNoItem',
  TBaseObject_WAbil_HP Name 'TBaseObject_WAbil_HP',
  TBaseObject_DeleteBagItem Name 'TBaseObject_DeleteBagItem',
  TBaseObject_AddCustomData Name 'TBaseObject_AddCustomData',
  TBaseObject_GetCustomData Name 'TBaseObject_GetCustomData',
  TBaseObject_SendMsg Name 'TBaseObject_SendMsg',
  TBaseObject_SendRefMsg Name 'TBaseObject_SendRefMsg',
  TBaseObject_SysMsg Name 'TBaseObject_SysMsg',
  TBaseObject_GetFrontPosition Name 'TBaseObject_GetFrontPosition',
  TBaseObject_GetRecallXY Name 'TBaseObject_GetRecallXY',
  TBaseObject_SpaceMove Name 'TBaseObject_SpaceMove',
  TBaseObject_FeatureChanged Name 'TBaseObject_FeatureChanged',
  TBaseObject_StatusChanged Name 'TBaseObject_StatusChanged',
  TBaseObject_GetFeatureToLong Name 'TBaseObject_GetFeatureToLong',
  TBaseObject_GetFeature Name 'TBaseObject_GetFeature',
  TBaseObject_GetCharColor Name 'TBaseObject_GetCharColor',
  TBaseObject_GetNamecolor Name 'TBaseObject_GetNamecolor',
  TBaseObject_GoldChanged Name 'TBaseObject_GoldChanged',
  TBaseObject_GameGoldChanged Name 'TBaseObject_GameGoldChanged',
  TBaseObject_MagCanHitTarget Name 'TBaseObject_MagCanHitTarget',
  TBaseObject_IsProtectTarget Name 'TBaseObject_IsProtectTarget',
  TBaseObject_IsAttackTarget Name 'TBaseObject_IsAttackTarget',
  TBaseObject_IsProperTarget Name 'TBaseObject_IsProperTarget',
  TBaseObject_IsProperFriend Name 'TBaseObject_IsProperFriend',
  TBaseObject_TrainSkillPoint Name 'TBaseObject_TrainSkillPoint',
  TBaseObject_GetAttackPower Name 'TBaseObject_GetAttackPower',
  TBaseObject_MakeSlave Name 'TBaseObject_MakeSlave',
  TBaseObject_MakeGhost Name 'TBaseObject_MakeGhost',
  TBaseObject_RefNameColor Name 'TBaseObject_RefNameColor',
  TBaseObject_AddItemToBag Name 'TBaseObject_AddItemToBag',
  TBaseObject_AddItemToStorage Name 'TBaseObject_AddItemToStorage',
  TBaseObject_ClearBagItem Name 'TBaseObject_ClearBagItem',
  TBaseObject_ClearStorageItem Name 'TBaseObject_ClearStorageItem',
  TBaseObject_SetHookGetFeature Name 'TBaseObject_SetHookGetFeature',
  TBaseObject_SetHookEnterAnotherMap Name 'TBaseObject_SetHookEnterAnotherMap',
  TBaseObject_SetHookObjectDie Name 'TBaseObject_SetHookObjectDie',
  TBaseObject_SetHookChangeCurrMap Name 'TBaseObject_SetHookChangeCurrMap',
  TBaseObject_GetPoseCreate Name 'TBaseObject_GetPoseCreate',
  TPlayObject_IsEnoughBag Name 'TPlayObject_IsEnoughBag',
  TPlayObject_nSoftVersionDate Name 'TPlayObject_nSoftVersionDate',
  TPlayObject_nSoftVersionDateEx Name 'TPlayObject_nSoftVersionDateEx',
  TPlayObject_dLogonTime Name 'TPlayObject_dLogonTime',
  TPlayObject_dwLogonTick Name 'TPlayObject_dwLogonTick',
  TPlayObject_nMemberType Name 'TPlayObject_nMemberType',
  TPlayObject_nMemberLevel Name 'TPlayObject_nMemberLevel',
  TPlayObject_nGameGold Name 'TPlayObject_nGameGold',
  TPlayObject_DecGameGold Name 'TPlayObject_DecGameGold',
  TPlayObject_nGamePoint Name 'TPlayObject_nGamePoint',
  TPlayObject_nPayMentPoint Name 'TPlayObject_nPayMentPoint',
  TPlayObject_nClientFlag Name 'TPlayObject_nClientFlag',
  TPlayObject_nSelectID Name 'TPlayObject_nSelectID',
  TPlayObject_nClientFlagMode Name 'TPlayObject_nClientFlagMode',
  TPlayObject_dwClientTick Name 'TPlayObject_dwClientTick',
  TPlayObject_wClientType Name 'TPlayObject_wClientType',
  TPlayObject_sBankPassword Name 'TPlayObject_sBankPassword',
  TPlayObject_nBankGold Name 'TPlayObject_nBankGold',
  TPlayObject_Create Name 'TPlayObject_Create',
  TPlayObject_Free Name 'TPlayObject_Free',
  TPlayObject_SendSocket Name 'TPlayObject_SendSocket',
  TPlayObject_SendDefMessage Name 'TPlayObject_SendDefMessage',
  TPlayObject_SendAddItem Name 'TPlayObject_SendAddItem',
  TPlayObject_SendDelItem Name 'TPlayObject_SendDelItem',
  TPlayObject_TargetInNearXY Name 'TPlayObject_TargetInNearXY',
  TPlayObject_SetBankPassword Name 'TPlayObject_SetBankPassword',
  TPlayObject_SetHookCreate Name 'TPlayObject_SetHookCreate',
  TPlayObject_GetHookCreate Name 'TPlayObject_GetHookCreate',
  TPlayObject_SetHookDestroy Name 'TPlayObject_SetHookDestroy',
  TPlayObject_GetHookDestroy Name 'TPlayObject_GetHookDestroy',
  TPlayObject_SetHookUserLogin1 Name 'TPlayObject_SetHookUserLogin1',
  TPlayObject_SetHookUserLogin2 Name 'TPlayObject_SetHookUserLogin2',
  TPlayObject_SetHookUserLogin3 Name 'TPlayObject_SetHookUserLogin3',
  TPlayObject_SetHookUserLogin4 Name 'TPlayObject_SetHookUserLogin4',
  TPlayObject_SetHookUserCmd Name 'TPlayObject_SetHookUserCmd',
  TPlayObject_GetHookUserCmd Name 'TPlayObject_GetHookUserCmd',
  TPlayObject_SetHookPlayOperateMessage Name 'TPlayObject_SetHookPlayOperateMessage',
  TPlayObject_GetHookPlayOperateMessage Name 'TPlayObject_GetHookPlayOperateMessage',
  TPlayObject_SetHookClientQueryBagItems Name 'TPlayObject_SetHookClientQueryBagItems',
  TPlayObject_SetHookClientQueryUserState Name 'TPlayObject_SetHookClientQueryUserState',
  TPlayObject_SetHookSendActionGood Name 'TPlayObject_SetHookSendActionGood',
  TPlayObject_SetHookSendActionFail Name 'TPlayObject_SetHookSendActionFail',
  TPlayObject_SetHookSendWalkMsg Name 'TPlayObject_SetHookSendWalkMsg',
  TPlayObject_SetHookSendHorseRunMsg Name 'TPlayObject_SetHookSendHorseRunMsg',
  TPlayObject_SetHookSendRunMsg Name 'TPlayObject_SetHookSendRunMsg',
  TPlayObject_SetHookSendDeathMsg Name 'TPlayObject_SetHookSendDeathMsg',
  TPlayObject_SetHookSendSkeletonMsg Name 'TPlayObject_SetHookSendSkeletonMsg',
  TPlayObject_SetHookSendAliveMsg Name 'TPlayObject_SetHookSendAliveMsg',
  TPlayObject_SetHookSendSpaceMoveMsg Name 'TPlayObject_SetHookSendSpaceMoveMsg',
  TPlayObject_SetHookSendChangeFaceMsg Name 'TPlayObject_SetHookSendChangeFaceMsg',
  TPlayObject_SetHookSendUseitemsMsg Name 'TPlayObject_SetHookSendUseitemsMsg',
  TPlayObject_SetHookSendUserLevelUpMsg Name 'TPlayObject_SetHookSendUserLevelUpMsg',
  TPlayObject_SetHookSendUserAbilieyMsg Name 'TPlayObject_SetHookSendUserAbilieyMsg',
  TPlayObject_SetHookSendUserStatusMsg Name 'TPlayObject_SetHookSendUserStatusMsg',
  TPlayObject_SetHookSendUserStruckMsg Name 'TPlayObject_SetHookSendUserStruckMsg',
  TPlayObject_SetHookSendUseMagicMsg Name 'TPlayObject_SetHookSendUseMagicMsg',
  TPlayObject_SetHookSendSocket Name 'TPlayObject_SetHookSendSocket',
  TPlayObject_SetHookSendGoodsList Name 'TPlayObject_SetHookSendGoodsList',
  TPlayObject_SetCheckClientDropItem Name 'TPlayObject_SetCheckClientDropItem',
  TPlayObject_SetCheckClientDealItem Name 'TPlayObject_SetCheckClientDealItem',
  TPlayObject_SetCheckClientStorageItem Name 'TPlayObject_SetCheckClientStorageItem',
  TPlayObject_SetCheckClientRepairItem Name 'TPlayObject_SetCheckClientRepairItem',
  TPlayObject_SetHookCheckUserItems Name 'TPlayObject_SetHookCheckUserItems',
  TPlayObject_SetHookRun Name 'TPlayObject_SetHookRun',
  TPlayObject_SetHookFilterMsg Name 'TPlayObject_SetHookFilterMsg',
  TPlayObject_GetPlayObjectTick Name 'TPlayObject_GetPlayObjectTick',
  TPlayObject_SetPlayObjectTick Name 'TPlayObject_SetPlayObjectTick',
  //TPlayObject_SetHookUserRunMsg Name 'TPlayObject_SetHookUserRunMsg',
  //TPlayObject_SetUserInPutInteger Name 'TPlayObject_SetUserInPutInteger',
  //TPlayObject_SetUserInPutString Name 'TPlayObject_SetUserInPutString',
  //TPlayObject_IncGold Name 'TPlayObject_IncGold',
  //TPlayObject_IncGameGold Name 'TPlayObject_IncGameGold',
  //TPlayObject_IncGamePoint Name 'TPlayObject_IncGamePoint',
  //TPlayObject_DecGold Name 'TPlayObject_DecGold',
  //TPlayObject_DecGameGold Name 'TPlayObject_DecGameGold',
  //TPlayObject_DecGamePoint Name 'TPlayObject_DecGamePoint',
  TNormNpc_sFilePath Name 'TNormNpc_sFilePath',
  TNormNpc_sPath Name 'TNormNpc_sPath',
  TNormNpc_GetLineVariableText Name 'TNormNpc_GetLineVariableText',
  TNormNpc_SetScriptActionCmd Name 'TNormNpc_SetScriptActionCmd',
  TNormNpc_GetScriptActionCmd Name 'TNormNpc_GetScriptActionCmd',
  TNormNpc_SetScriptConditionCmd Name 'TNormNpc_SetScriptConditionCmd',
  TNormNpc_GetScriptConditionCmd Name 'TNormNpc_GetScriptConditionCmd',
  TNormNpc_SetScriptAction Name 'TNormNpc_SetScriptAction',
  TNormNpc_GetScriptAction Name 'TNormNpc_GetScriptAction',
  TNormNpc_SetScriptCondition Name 'TNormNpc_SetScriptCondition',
  TNormNpc_GetScriptCondition Name 'TNormNpc_GetScriptCondition',
  TNormNpc_GetManageNpc Name 'TNormNpc_GetManageNpc',
  TNormNpc_GetFunctionNpc Name 'TNormNpc_GetFunctionNpc',
  TNormNpc_GotoLable Name 'TNormNpc_GotoLable',
  TMerchant_GoodsList Name 'TMerchant_GoodsList',
  TMerchant_GetItemPrice Name 'TMerchant_GetItemPrice',
  TMerchant_GetUserPrice Name 'TMerchant_GetUserPrice',
  TMerchant_GetUserItemPrice Name 'TMerchant_GetUserPrice',
  TMerchant_SetHookClientGetDetailGoodsList Name 'TMerchant_SetHookClientGetDetailGoodsList',
  //TMerchant_SetCheckUserSelect Name 'TMerchant_SetCheckUserSelect',
  //TMerchant_GetCheckUserSelect Name 'TMerchant_GetCheckUserSelect',
  TMapManager_FindMap Name 'TMapManager_FindMap',
  TEnvirnoment_GetRangeBaseObject Name 'TEnvirnoment_GetRangeBaseObject',
  TEnvirnoment_boCANRIDE Name 'TEnvirnoment_boCANRIDE',
  TEnvirnoment_boCANBAT Name 'TEnvirnoment_boCANBAT',
  TUserEngine_Create Name 'TUserEngine_Create',
  TUserEngine_Free Name 'TUserEngine_Free',
  TUserEngine_GetUserEngine Name 'TUserEngine_GetUserEngine',
  TUserEngine_GetPlayObject Name 'TUserEngine_GetPlayObject',
  TUserEngine_GetLoadPlayList Name 'TUserEngine_GetLoadPlayList',
  //TUserEngine_GetPlayObjectList Name 'TUserEngine_GetPlayObjectList',
  TUserEngine_GetLoadPlayCount Name 'TUserEngine_GetLoadPlayCount',
  TUserEngine_GetPlayObjectCount Name 'TUserEngine_GetPlayObjectCount',
  TUserEngine_GetStdItemByName Name 'TUserEngine_GetStdItemByName',
  TUserEngine_GetStdItemByIndex Name 'TUserEngine_GetStdItemByIndex',
  TUserEngine_CopyToUserItemFromName Name 'TUserEngine_CopyToUserItemFromName',
  TUserEngine_GetStdItemList Name 'TUserEngine_GetStdItemList',
  TUserEngine_SetHookRun Name 'TUserEngine_SetHookRun',
  TUserEngine_GetHookRun Name 'TUserEngine_GetHookRun',
  TUserEngine_SetHookClientUserMessage Name 'TUserEngine_SetHookClientUserMessage',
  TUserEngine_GetMapMonster Name 'TUserEngine_GetMapMonster',
  //TUserEngine_GetEngineLong Name 'TUserEngine_GetEngineLong',
  M2Share_GetNoClearMonList Name 'M2Share_GetNoClearMonList',

  TGuild_RankList Name 'TGuild_RankList',
  TItemUnit_GetItemAddValue Name 'TItemUnit_GetItemAddValue',
  TMagicManager_GetMagicManager Name 'TMagicManager_GetMagicManager',
  TMagicManager_DoSpell Name 'TMagicManager_DoSpell',
  TMagicManager_MPow Name 'TMagicManager_MPow',
  TMagicManager_GetPower Name 'TMagicManager_GetPower',
  TMagicManager_GetPower13 Name 'TMagicManager_GetPower13',
  TMagicManager_GetRPow Name 'TMagicManager_GetRPow',
  TMagicManager_IsWarrSkill Name 'TMagicManager_IsWarrSkill',
  TMagicManager_MagBigHealing Name 'TMagicManager_MagBigHealing',
  TMagicManager_MagPushArround Name 'TMagicManager_MagPushArround',
  TMagicManager_MagPushArroundTaos Name 'TMagicManager_MagPushArroundTaos',
  TMagicManager_MagTurnUndead Name 'TMagicManager_MagTurnUndead',
  TMagicManager_MagMakeHolyCurtain Name 'TMagicManager_MagMakeHolyCurtain',
  TMagicManager_MagMakeGroupTransparent Name 'TMagicManager_MagMakeGroupTransparent',
  TMagicManager_MagTamming Name 'TMagicManager_MagTamming',
  TMagicManager_MagSaceMove Name 'TMagicManager_MagSaceMove',
  TMagicManager_MagMakeFireCross Name 'TMagicManager_MagMakeFireCross',
  TMagicManager_MagBigExplosion Name 'TMagicManager_MagBigExplosion',
  TMagicManager_MagElecBlizzard Name 'TMagicManager_MagElecBlizzard',
  TMagicManager_MabMabe Name 'TMagicManager_MabMabe',
  TMagicManager_MagMakeSlave Name 'TMagicManager_MagMakeSlave',
  TMagicManager_MagMakeSinSuSlave Name 'TMagicManager_MagMakeSinSuSlave',
  TMagicManager_MagWindTebo Name 'TMagicManager_MagWindTebo',
  TMagicManager_MagGroupLightening Name 'TMagicManager_MagGroupLightening',
  TMagicManager_MagGroupAmyounsul Name 'TMagicManager_MagGroupAmyounsul',
  TMagicManager_MagGroupDeDing Name 'TMagicManager_MagGroupDeDing',
  TMagicManager_MagGroupMb Name 'TMagicManager_MagGroupMb',
  TMagicManager_MagHbFireBall Name 'TMagicManager_MagHbFireBall',
  TMagicManager_MagLightening Name 'TMagicManager_MagLightening',
  TMagicManager_SetHookDoSpell Name 'TMagicManager_SetHookDoSpell',
  TRunSocket_CloseUser Name 'TRunSocket_CloseUser',
  TRunSocket_SetHookExecGateMsgOpen Name 'TRunSocket_SetHookExecGateMsgOpen',
  TRunSocket_SetHookExecGateMsgClose Name 'TRunSocket_SetHookExecGateMsgClose',
  TRunSocket_SetHookExecGateMsgEeceiveOK Name 'TRunSocket_SetHookExecGateMsgEeceiveOK',
  TRunSocket_SetHookExecGateMsgData Name 'TRunSocket_SetHookExecGateMsgData',
  TMemoryManager_Get Name 'TMemoryManager_Get',
  TMemoryManager_AllocMemCount Name 'TMemoryManager_AllocMemCount',
  TMemoryManager_AllocMemSize Name 'TMemoryManager_AllocMemSize';
}

begin
  Application.Initialize;
  Application.HintPause := 100;
  Application.HintShortPause := 100;
  Application.HintHidePause := 5000;
  Application.CreateForm(TFrmMain, FrmMain);
  Application.CreateForm(TFrmSrvMsg, FrmSrvMsg);
  Application.CreateForm(TFrmMsgClient, FrmMsgClient);
  Application.CreateForm(TFrmIDSoc, FrmIDSoc);
  Application.CreateForm(TFrmServerValue, FrmServerValue);
  Application.Run;
end.

